#pragma once

#include <cstdint>

#include "lora.hpp"

namespace protocol {

enum class PacketType : uint8_t { HANDSHAKE_REQ, HANDSHAKE_ACK, DATA };

constexpr uint8_t MAGIC = 0x4E;

#pragma pack(push, 1)
struct PacketHeader {
  uint8_t magic = MAGIC;  // fixed value to identify start of packet
  // uint8_t address;
  uint32_t sessionId;  // random value generated by remote on startup
  PacketType type;
  uint16_t length;  // length of payload in bytes
  // uint32_t seqNum; // sequence number
};
#pragma pack(pop)

// add payload structs later as needed
// add templated encode() and decode() for packets eventually

#pragma pack(push, 1)
struct DataPacket {
  PacketHeader header;
  etl::vector<uint8_t, lora::Lora::RADIO_FIFO_SIZE - sizeof(PacketHeader)> payload;
};
#pragma pack(pop)

};  // namespace protocol